//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latenite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lucida Console, 8.25pt")]
        public global::System.Drawing.Font EditorFont {
            get {
                return ((global::System.Drawing.Font)(this["EditorFont"]));
            }
            set {
                this["EditorFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point IDE_Location {
            get {
                return ((global::System.Drawing.Point)(this["IDE_Location"]));
            }
            set {
                this["IDE_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Editor_Back_Colour {
            get {
                return ((global::System.Drawing.Color)(this["Editor_Back_Colour"]));
            }
            set {
                this["Editor_Back_Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Editor_Text_Colour {
            get {
                return ((global::System.Drawing.Color)(this["Editor_Text_Colour"]));
            }
            set {
                this["Editor_Text_Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.Forms.FormWindowState IDE_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["IDE_WindowState"]));
            }
            set {
                this["IDE_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size IDE_ClientSize {
            get {
                return ((global::System.Drawing.Size)(this["IDE_ClientSize"]));
            }
            set {
                this["IDE_ClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.asm;*.z80;*.inc;*.cmd;*.txt;*.debug")]
        public string Project_Filter {
            get {
                return ((string)(this["Project_Filter"]));
            }
            set {
                this["Project_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color Syntax_Directive {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Directive"]));
            }
            set {
                this["Syntax_Directive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color Syntax_Z80 {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Z80"]));
            }
            set {
                this["Syntax_Z80"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkViolet")]
        public global::System.Drawing.Color Syntax_Routine {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Routine"]));
            }
            set {
                this["Syntax_Routine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color Syntax_String {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_String"]));
            }
            set {
                this["Syntax_String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color Syntax_Comment {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Comment"]));
            }
            set {
                this["Syntax_Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color Syntax_Label {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Label"]));
            }
            set {
                this["Syntax_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43, 145, 175")]
        public global::System.Drawing.Color Syntax_Register {
            get {
                return ((global::System.Drawing.Color)(this["Syntax_Register"]));
            }
            set {
                this["Syntax_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.asm;*.z80;*.inc")]
        public string Editor_Syntax_Files_To_Highlight {
            get {
                return ((string)(this["Editor_Syntax_Files_To_Highlight"]));
            }
            set {
                this["Editor_Syntax_Files_To_Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Editor_AutoIndent {
            get {
                return ((bool)(this["Editor_AutoIndent"]));
            }
            set {
                this["Editor_AutoIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Editor_AutoSave {
            get {
                return ((bool)(this["Editor_AutoSave"]));
            }
            set {
                this["Editor_AutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Editor_CRLF {
            get {
                return ((bool)(this["Editor_CRLF"]));
            }
            set {
                this["Editor_CRLF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IDE_Multiple_Tabs {
            get {
                return ((bool)(this["IDE_Multiple_Tabs"]));
            }
            set {
                this["IDE_Multiple_Tabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color Debug_Breakpoint_Back {
            get {
                return ((global::System.Drawing.Color)(this["Debug_Breakpoint_Back"]));
            }
            set {
                this["Debug_Breakpoint_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Debug_Current_Fore {
            get {
                return ((global::System.Drawing.Color)(this["Debug_Current_Fore"]));
            }
            set {
                this["Debug_Current_Fore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Debug_Current_Back {
            get {
                return ((global::System.Drawing.Color)(this["Debug_Current_Back"]));
            }
            set {
                this["Debug_Current_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Debug_Breakpoint_Fore {
            get {
                return ((global::System.Drawing.Color)(this["Debug_Breakpoint_Fore"]));
            }
            set {
                this["Debug_Breakpoint_Fore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int IDE_Output_Size {
            get {
                return ((int)(this["IDE_Output_Size"]));
            }
            set {
                this["IDE_Output_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320")]
        public int IDE_Help_Size {
            get {
                return ((int)(this["IDE_Help_Size"]));
            }
            set {
                this["IDE_Help_Size"] = value;
            }
        }
    }
}
